name: Run

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python3 hash.py ./nrfcloud.ca.pem > nrfcloud.ca.pem.sha256
      - run: test `cat nrfcloud.ca.pem.sha256` = "6F3214857B50EDD5CAA9938188BBAB5952BF3E805724FD428DD166FFD79DDCCB"

      - run: python3 hash.py ./CLIENT_CERT.pem > CLIENT_CERT.pem.sha256
      - run: test `cat CLIENT_CERT.pem.sha256` = "9081A557198ECB7DC7A0F73E73246B17E305C4D332154ED52597F2F5C84B444F"
