name: Run

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python3 hash.py ./nrfcloud.ca.pem > nrfcloud.ca.pem.sha256
      - run: test `cat nrfcloud.ca.pem.sha256` = "B411BFD55AC7075B65FD64CC75A4AA7FA3513014BFF6C90D5E0AA34DE533917B"

      - run: python3 hash.py ./CLIENT_CERT.pem > CLIENT_CERT.pem.sha256
      - run: test `cat CLIENT_CERT.pem.sha256` = "4861CA4836312FEECB270E96E5133527AAC7BD99F94FA91FEBE532163685FC4D"
